# Usamos la imagen oficial de Nginx como base
FROM nginx:alpine

# Copiar el contenido del directorio 'frontend' al directorio de Nginx para servir la página
COPY . /usr/share/nginx/html

# Exponer el puerto 80 para servir la aplicación
EXPOSE 80
